name: Codecov

on: [push, pull_request]

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Code coverage
    container:
      image: registry.fedoraproject.org/fedora:latest
      options: --privileged
    steps:
      - name: Install git for checkout
        run: dnf -y install git

      - name: Checkout
        uses: actions/checkout@v6
        with:
          # needed for codecov
          fetch-depth: 0

      - name: Setup coverage environment
        run: ./tests/prepare-fedora-test-environment.sh

      - name: Run tests and collect coverage
        run: |
          . "$HOME/.cargo/env"
          make coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          file: .coverage/coverage.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
